admin_panel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^ajax/check/user/$', views.check_user, name='check_user'),
    url(r'^ajax/remove_good/$', views.ajax_remove_good, name='ajax_remove_good'),
    url(r'^ajax/move_up/$', views.ajax_move_up, name='ajax_move_up'),
    url(r'^ajax/move_down/$', views.ajax_move_down, name='ajax_move_down'),
    url(r'^add_good/', views.add_good, name='add_good'),
    url(r'^edit_good/', views.edit_good, name='edit_good'),
	url(r'^ajax/delete_image/', views.ajax_delete_image, name='ajax_delete_image'),
]

main/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ajax/get_goods/$', views.ajax_get_goods, name='ajax_get_goods'),
    url(r'^ajax/get_images/$', views.ajax_get_images, name='ajax_get_images'),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roofing/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', include('admin_panel.urls')),
    url(r'^', include('main.urls')),
]

admin_panel/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

class Image(models.Model):
	image = models.FileField(upload_to='img/%Y/%m/%d', blank=True)

class Good(models.Model):
	name = models.CharField(max_length=255)
	description = models.TextField()
	price = models.DecimalField(max_digits=6, decimal_places=2)
	images = models.ManyToManyField(Image)

admin_panel/forms.py
from django import forms
from main.models import Good

class GoodForm(forms.ModelForm):
	class Meta:
		model = Good
		fields = ('name', 'description', 'price', 'images')

admin_panel/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import auth
from django.shortcuts import redirect
from main.models import Good
from main.models import Image
from admin_panel.forms import GoodForm
import os

# Create your views here.

def index(request):
    if request.user.is_authenticated():
        goods = Good.objects.all()
        return render(request, 'admin_panel/index.html', { 'goods' : goods })
    else:
        return render(request, 'admin_panel/login.html')

def check_user(request):
    if request.method == "POST":
        username = request.POST.get('user_login','')
        password = request.POST.get('user_password','')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                request.session.set_expiry(86400)
                login(request, user)
                return HttpResponse('yes', content_type='text/html')
        return HttpResponse('', content_type='text/html')
    else:
        return HttpResponse('', content_type='text/html')

def logout(request):
    auth.logout(request)
    return redirect('/admin/')

def add_good(request):
    if request.method == 'POST': 
        name = request.POST.get('name')
        description = request.POST.get('description')
        price = float(request.POST.get('price'))
        images = request.FILES.getlist('images')
        
        good = Good()
        good.name = name
        good.description = description
        good.price = price
        good.save()

        for image in images:
            imageModel = Image()
            imageModel.image = image
            imageModel.save()
            good.images.add(imageModel)

        return redirect('/admin/')
    else:
        pass
    return render(request, 'admin_panel/good.html')

def edit_good(request):

    if request.method == 'POST':
        good = Good.objects.filter(id=int(request.POST.get("good-id")))[0]
        good.name = request.POST.get("name")
        good.description = request.POST.get("description")
        good.price = float(request.POST.get("price"))
        good.save()

        if len(request.FILES) != 0:
            images = request.FILES.getlist('images')
            for image in images:
                imageModel = Image()
                imageModel.image = image
                imageModel.save()
                good.images.add(imageModel)

        return redirect('/admin/')
    else:
        good_id = request.GET.get('good-id')

        good = Good.objects.get(id=int(good_id))
        
        name = good.name
        description = good.description
        price = good.price
        images = good.images.all()

        # form = GoodForm()
    
    return render(request, 'admin_panel/good.html', { 'good_id' : good_id, 'state' : 'edit', 'name' : name, 'price' : price, 'images' : images, 'description' : description })

def ajax_remove_good(request):
    good = Good.objects.filter(id=int(request.POST.get('id')))
    for some_good in good:
        for image in some_good.images.all():
            image.delete()
    good.delete()
    return HttpResponse('OK')

def ajax_move_up(request):
    try:
        good_higher = Good.objects.filter(id__lt=int(request.POST.get("id"))).order_by('-id')[0]
        good_current = Good.objects.filter(id=int(request.POST.get("id")))[0]
        
        name = good_current.name
        description = good_current.description
        price = good_current.price
        image = good_current.image
        
        good_current.name = good_higher.name
        good_current.description = good_higher.description
        good_current.price = good_higher.price
        good_current.image = good_higher.image
        good_current.save()
       
        good_higher.name = name
        good_higher.description = description
        good_higher.price = price
        good_higher.image = image
        good_higher.save()
    except Exception:
        pass

    return HttpResponse(good_higher.id)

def ajax_move_down(request):
    try:
        good_lower = Good.objects.filter(id__gt=int(request.POST.get("id"))).order_by('id')[0]
        good_current = Good.objects.filter(id=int(request.POST.get("id")))[0]
        
        name = good_current.name
        description = good_current.description
        price = good_current.price
        image = good_current.image
        
        good_current.name = good_lower.name
        good_current.description = good_lower.description
        good_current.price = good_lower.price
        good_current.image = good_lower.image
        good_current.save()
       
        good_lower.name = name
        good_lower.description = description
        good_lower.price = price
        good_lower.image = image
        good_lower.save()
    except Exception:
        pass

    return HttpResponse(good_lower.id)

def ajax_delete_image(request):
    try:
        some_id = request.POST.get('some_id')
        Image.objects.filter(id=int(some_id)).delete()
    except:
        return HttpResponse('no')
    return HttpResponse('ok')

admin_panel/templates/admin_panel/good.html
{% extends 'admin_panel/layout.html' %}

{% block content %}
	
	{% load static %}

	<link rel="stylesheet" type="text/css" href="{% static "main/css/good.css" %}">

	<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
	<link rel="stylesheet" type="text/css" href="http://kenwheeler.github.io/slick/slick/slick-theme.css"/>

	<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
				
	<div class="container">
		
		{% if state == "edit" %}
		    <h2>Редагувння товару</h2>
		    <hr style="border-color: white;">
		    <form method="post" action="/admin/edit_good/" enctype="multipart/form-data" id="good_form">
		{% else %}
	        <h2>Створення товару</h2>
		    <hr style="border-color: white;">
	        <form method="post" action="/admin/add_good/" enctype="multipart/form-data" id="good_form">
		{% endif%}

				{% csrf_token %}
				<p><label for="id_name">Назва</label> <input id="id_name" maxlength="255" name="name" type="text" required="" class="form-control"></p>
				<p><label for="id_description">Опис</label> <textarea cols="40" id="id_description" name="description" rows="10" required="" class="form-control"></textarea></p>
				<p><label for="id_price">Ціна</label> <input id="id_price" name="price" step="0.01" type="number" required="" class="form-control"></p>
				<p><label for="id_images">Додати зображення</label> <input multiple="multiple" type="file" id="id_images" name="images" class="form-control"></p>
	        	<input type="hidden" name="good-id" value="{{ good_id }}">
	        {% if state == "edit" %}
	        	<p>Старі зображення: </p>
		        <!--
		        <img style="margin-bottom: 20px" src="" id="old_image">
		        <br>
		        <input id="some_id" type="hidden" name="some_id" />
	        	-->
				<div class="container">
					<div id="myCarousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
						    {% for image in images %}
								{% if forloop.first %}
								    <li data-target="#myCarousel" data-slide-to="{{forloop.counter0}}" class="active"></li>
								{% else %}
								    <li data-target="#myCarousel" data-slide-to="{{forloop.counter0}}"></li>
								{% endif %}
							{% endfor %}
					    </ol>
						<div class="carousel-inner" role="listbox">
							{% for image in images %}
								{% if forloop.first %}
									<div class="item active">
										<img src="/media/{{ image.image }}" alt="slide">
										<a id="{{ image.id }}" class="btn btn-danger remove-image"><span class="glyphicon glyphicon-trash"></span></a>
									</div>
								{% else %}
									<div class="item">
										<img src="/media/{{ image.image }}" alt="slide">
										<a id="{{ image.id }}" class="btn btn-danger remove-image"><span class="glyphicon glyphicon-trash"></span></a>
									</div>
								{% endif %}
							{% endfor %}
						</div>
						<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
							<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
							<span class="sr-only">Previous</span>
						</a>
						<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
							<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
							<span class="sr-only">Next</span>
						</a>
					</div>
				</div>

	        {% endif %}
	        <hr style="border-color: white;">
	        <button class="btn btn-primary" class="form-control" type="submit" id="submit_good ">Зберегти</button>
		</form>

	</div>

	<script type="text/javascript">
		$( document ).ready(function(){

			$.ajaxSetup({
		  		data: { csrfmiddlewaretoken: '{{ csrf_token }}' },
			});

			if("{{ state }}"=="edit"){
				// alert('edit');
				$("#some_id").val("{{ some_id }}");
				$("#id_name").val("{{ name }}");
				$("#id_description").val(`{{ description }}`);
				$("#id_price").val("{{ price }}");


			}

			$(".remove-image").on('click', function(){
				var some_id = $(this).attr("id");
				$.post("/admin/ajax/delete_image/", { 'some_id' : some_id }, function(data){
					if(data == "ok"){
						$(".carousel-indicators li").last().remove();
						// $('#myCarousel').carousel('next');
						var $carousel = $("#myCarousel");
						var ActiveElement = $carousel.find('.item.active');
						  ActiveElement.remove();
						  var NextElement = $carousel.find('.item').first();
						  NextElement.addClass('active');
						$carousel.find("ol li").removeClass("active");
						  $carousel.find("ol li").first().addClass("active");
					} else{
						alert("Sorry, some error");	
					}
				});
			});

			$("#id_name").addClass("form-control");
			$("#id_description").addClass("form-control");
			$("#id_price").addClass("form-control");
			$("#id_image").addClass("form-control");

		});

	</script>
	
{% endblock %}

admin_panel/templates/admin_panel/index.html
{% extends 'admin_panel/layout.html' %}

{% block content %}
	{% load static %}
	
	<div class="container body-content">
		
		<table id="goods" class="table table-hover table-striped ">
                <thead>
                  <tr id="select-all-tr">
                    <th>#</th>
                    <th>Назва</th>
                    <th>Опис</th>
                    <th>Ціна</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                {% for good in goods %}
                    <tr class="good-row" id="{{ good.id }}">
                        <td class="good_position">{{ forloop.counter }}</td>
                        <td>{{ good.name }}</td>
                        <td>{{ good.description|slice:":50" }}</td>
                        <td>{{ good.price }}</td>
                        <td style="display: inline-block;">
                            <form action="/admin/edit_good" method="GET"> 
                                <button class="btn btn-success edit_good" type="submit">Редагувати <span class="glyphicon glyphicon-edit"></span></button>
                                <input type="hidden" value="{{ good.id }}" name="good-id"/>
                            </form>
                        </td>
                        <td>
                            <button type="button" class="btn btn-info move_up"><span class="glyphicon glyphicon-arrow-up"></span></button>
                            <button type="button" class="btn btn-info move_down"><span class="glyphicon glyphicon-arrow-down"></span></button>
                            <button type="button" class="btn btn-danger remove_good"><span class="glyphicon glyphicon-trash"></span></button>
                        </td>
                    </tr>
                {% endfor %}
        
            </tbody>
        </table>
        <a class="btn btn-primary" href="/admin/add_good"><span class="glyphicon glyphicon-plus"></span> Додати новий</a>
	</div>

    <script type="text/javascript">
        
        $(document).ready(function(){

            $("#goods").on('click',".remove_good", function(e){
                var tr = $(this).closest("tr");
                $.ajax({
                    url : "/admin/ajax/remove_good/",
                    data : { 
                        id : tr.attr("id"),
                        csrfmiddlewaretoken : "{{ csrf_token }}",
                    },
                    type : "post",
                    success : function(data){
                        tr.remove();
                    }
                });
            });

            $("#goods").on('click', ".move_up", function(e){
                var tr = $(this).closest("tr");
                $.ajax({
                    url : "/admin/ajax/move_up/",
                    data : { 
                        id : tr.attr("id"),
                        csrfmiddlewaretoken : "{{ csrf_token }}",
                    },
                    type : "post",
                    success : function(data){
                        var tr1 = $("#"+data);
                        var html = tr1.html();
                        tr1.html( tr.html() );
                        tr.html( html );

                        var tr_position = tr.find(".good_position").text();
                        // alert(tr_position);
                        tr.find(".good_position").text(tr1.find(".good_position").text());
                        tr1.find(".good_position").text(tr_position);
                    }
                });
            });

            $("#goods").on('click',".move_down", function(e){
                var tr = $(this).closest("tr");
                $.ajax({
                    url : "/admin/ajax/move_down/",
                    data : { 
                        id : tr.attr("id"),
                        csrfmiddlewaretoken : "{{ csrf_token }}",
                    },
                    type : "post",
                    success : function(data){
                        var tr1 = $("#"+data);
                        var html = tr1.html();
                        tr1.html( tr.html() );
                        tr.html( html );

                        var tr_position = tr.find(".good_position").text();
                        tr.find(".good_position").text(tr1.find(".good_position").text());
                        tr1.find(".good_position").text(tr_position);
                    }
                });
            });        


        });

        
    </script>

   
	
{% endblock %}

admin_panel/templates/admin_panel/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin panel</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {% load static %}

    <link rel="shortcut icon" type="image/png" href="{% static "admin_panel/favicon.ico" %}">
    <link href="{% static "admin_panel/css/admin.css" %}" rel="stylesheet">
    <style>
        body {
            background: #eee !important;  
        }

        .wrapper {  
            margin-top: 80px;
            margin-bottom: 80px;
        }
    </style>
  </head>

  <script src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


  <body>
    
    <nav class="navbar navbar-own">
      <div class="container-fluid" id="main-header-title">
        <ul class="nav nav-pills navbar-left">
            <li id="index">
                <a href="/admin/">
                    <span>Головна</span>
                </a>
            </li>
          </ul>
          <ul class="nav nav-pills navbar-right">
              <li><a href="/admin/logout" class="btn-exit">Вийти</a></li>
          </ul>
      </div>
    </nav>
  
    {% block content %}
    {% endblock %}

  </body>
</html>

admin_panel/templates/admin_panel/login.html
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Login</title>
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		{% load static %}

		<link rel="shortcut icon" type="image/png" href="{% static "admin_panel/favicon.ico" %}">
		<link href="{% static "admin_panel/css/admin.css" %}" rel="stylesheet">
		<style>
            body {
                background: #eee !important;	
            }

            .wrapper {	
                margin-top: 80px;
                margin-bottom: 80px;
            }
        </style>
	</head>
	
	<body class="en">
		<div class="container wrapper">
			<form id="login_form" role="form" class="form-signin" name="login-form" action="/" method="POST">
		        <h3 class="form-signin-heading" style="text-align:center">Log in: </h3>
		        <label for="inputEmail" class="sr-only">Login</label>
		        <input style="margin-bottom: 20px;" type="text" id="user_login" name="user_login" class="form-control" placeholder="Login" required="" autofocus="">
		        <label for="inputPassword" class="sr-only">Password</label>
		        <input type="password" name="user_password" id="user_password" class="form-control" placeholder="Password" required="">
		        <input type="hidden" value="user_code" name="user_code" id="user_code">
	        </form>
	        <button class="btn btn-lg btn-primary btn-block submit-button" type="submit">Enter</button>
        
	        <div class="validation">
	        	
	        </div>

		</div>
        
	    <footer class="footer">
		    <div>
			    Developed by <a href="http://www.aits.ua/" target="_blank"><span class="reserved"> AITS</span></a>
		    </div>
	    </footer>
	    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

		<script>
            $('#user_password').keypress(function (e) {
                var key = e.which;
                if(key === 13)
                {
                   $(".submit-button").click();
                }
            }); 
            $(".submit-button").click(function(){
                console.log("sss");
                $(".validation").html("");
                $.ajax({
                    type: "post",
                    url: "/admin/ajax/check/user/",
                    cache: false,    
                    data: {
                    	'user_login': $("#user_login").val(),
                    	'user_password': $("#user_password").val(),
                    	'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    success: function(response){
                        if(response === "" || response === null){
                            $(".validation").html("<span style='color:red'>Bad login or password</span>");
                        }
                        else {
                            $("#user_code").val(response);
                            location.href = "/admin/"
                        }
                    }, 
                    error: function(response){      
                        console.log(response);
                    }
                });
            });  
        </script>

	</body>
</html>